version: 0.0
os: linux

files:
    - source: /
      destination: /home/ubuntu/DAVODA_API_Gateway
      overwrite: true

permissions:
    - object: /home/ubuntu/DAVODA_API_Gateway
      owner: ubuntu
      group: ubuntu
      mode: 777

hooks:
    AfterInstall:
        - location: scripts/start_server.sh
          timeout: 60
          runas: ubuntu
